version: "{build}"

shallow_clone: true

environment:
  global:
    CYGWIN: C:\Cygwin
    CYGSH: C:\Cygwin\bin\bash -lc
  matrix:
    - {SYSTEM: cygwin, COMPILER: 4.01}
    - {SYSTEM: cygwin, COMPILER: 4.02}

install:
  - appveyor DownloadFile https://aantron.github.io/binaries/%SYSTEM%/x86/ocaml/%COMPILER%/install.ps1
  - ps: .\install.ps1
  - appveyor DownloadFile https://aantron.github.io/binaries/%SYSTEM%/x86/camlp4/%COMPILER%/install.ps1
  - ps: .\install.ps1
  - appveyor DownloadFile https://aantron.github.io/binaries/%SYSTEM%/x86/opam/1.2.2/install.ps1
  - ps: .\install.ps1
  - utils\appveyor-%SYSTEM%-install.bat

build_script:
  - utils\appveyor-%SYSTEM%-build.bat
